### ISSUE TITLE
Reformatting for different resolution

### ISSUE THREAD

**Issue by D-Buz** [nbclark/hqcheat#14]
I saw the troubleshooting that reformatting is on line 108-113, but I can't figure out how to rewrite the code so it works for my iPhone 6S.... Anyone who knows, please help!

**Comment by apates5** [comment]
Hey! Just wondering, what did you change the numbers to in the script? I have a 6s and still haven't found out the right numbers. Thanks

**Comment by D-Buz** [comment]
Replace Line 33 with the following:   var config1 = { width: 1051 - left - left, height: 1999 - top - bottom, top, left };

**Comment by D-Buz** [comment]
@apates5 ^^^^

**Comment by D-Buz** [comment]
@apates5 I meant to say line 32
