### ISSUE TITLE
Bot was working prefect and then....

### ISSUE THREAD

**Issue by D-Buz** [nbclark/hqcheat#15]
So i figured out everything to make the bot run perfect and it did, when all of a sudden it stopped pull results from google! Now it just looks like this, instead of like before with a completed google search:
<img width="524" alt="screen shot 2018-01-25 at 8 38 21 pm" src="https://user-images.githubusercontent.com/35752161/35421192-c61ed9f0-020f-11e8-8c3a-c25a9deda366.png">
Please help! @nbclark

**Comment by nbclark** [comment]
Nice work fixing the resolution - You are likely getting blocked by google. Did you run the script many many times in a row?

**Comment by D-Buz** [comment]
Thanks, sorry i bothered u so much lol

Yeah i did run it a lot while fixing resolution issue... If i turn on VPN will that do the trick?

**Comment by nbclark** [comment]
No worries - VPN should work fine to unblock you. Though you might get blocked again if you run it too many times.

**Comment by D-Buz** [comment]
VPN Worked! Thanks again!
