### ISSUE TITLE
Tesseract Confuses letters

### ISSUE THREAD

**Issue by D-Buz** [nbclark/hqcheat#16]
Tersseract sometimes adds non existent spaces and confuses W with VV. I'll be uploading a version of the bot with a custom pic processer, and slight edits in the code to work faster. Credit will be given to @nbclark and will link to his page, it'll be an improved bot based on his code! Big thanks to @nbclark for a great foundation.

**Comment by D-Buz** [comment]
It will also have added to the README formatting for most iPhones.

**Comment by AlexPerez01** [comment]
Where can i find this improved version?
