### ISSUE TITLE
scoped count: Null

### ISSUE THREAD

**Issue by Warnoe** [nbclark/hqcheat#2]
I have gotten the program up and running on my Mac today, however when I take a snapshot and it begins to process, no google results show up and the scoped count comes up as null. I do not know the cause of this and was wondering if you could give me some advice on how to fix it.

**Comment by Warnoe** [comment]
Here is an example of my problem
<img width="574" alt="screen shot 2018-01-01 at 3 49 58 pm" src="https://user-images.githubusercontent.com/34990454/34471014-8137b77e-ef0b-11e7-9d46-6bf4abdbe80a.png">

**Comment by Warnoe** [comment]
I figured it out, it turns out that I just needed to update the various modules such as cheerio and restart my Mac. Great script by the way!

**Comment by CJerome5** [comment]
@Warnoe sorry for re-opening the issue but, can I add you on skype for further questions about the program?

**Comment by Warnoe** [comment]
Hey, @CJerome5 I honestly have almost no clue when it comes to Java Script... I just did some random troubleshooting techniques that I though may work. My best recommendation for getting the program to work is to ensure that you have node installed (https://nodejs.org/en/) then use the command npm install (each module you want to install eg. cheerio) in the terminal to ensure they are installed and updated. after doing that I recommend a restart of the computer.

**Comment by Warnoe** [comment]
I dont know if this did anything either, but I did change the file extension from yarn.lock to just yarnlock so just erase the period, then I opened the file, then after the terminal window was finished I changed the file extension back to yarn.lock and restarted my computer
