### ISSUE TITLE
Stuck at node index.js

### ISSUE THREAD

**Issue by apates5** [nbclark/hqcheat#4]
I just installed tesseract, and installed node and nmp, and have all the files from github downloaded, but when I run this it is just stuck when I press enter. Waited a few hours and still nothing. Does anyone know a fix?
<img width="654" alt="screen shot 2018-01-01 at 9 27 24 pm" src="https://user-images.githubusercontent.com/31677811/34473851-b3d0c81c-ef45-11e7-8773-60e53c26dda3.png">

**Comment by Warnoe** [comment]
Do you have all of the various modules installed using the command npm install ____________
then use the command cd "(complete file directory)" then hit enter
then you should be able to do the node index.js

**Comment by Warnoe** [comment]
also have you changed the user in the index.js? if not scroll down to the place in code where it has Nicholas in the User and replace with your user
Now you should be able to leave the terminal running with the above instructions and use the snapshot  tool and you will be crushing it at HQ trivia

**Comment by apates5** [comment]
How can I change the the user to my name?

**Comment by apates5** [comment]
Wait the command command cd what file directory do I have to use?

**Comment by Warnoe** [comment]
the folder where the files are
for example mine is /Users/XXXXXXXXXX/Desktop/hqcheat-master

**Comment by apates5** [comment]
This is the error I got when installing any module. It's saying that there is no package.json, but it is in it when i looked in the folder. So I am confused why it doesn't work?<img width="759" alt="screen shot 2018-01-02 at 4 18 38 pm" src="https://user-images.githubusercontent.com/31677811/34500504-05b07ea0-efd9-11e7-8e9e-cea9a102ff86.png">

**Comment by pjerryhu** [comment]
Very helpful. Thank you @Warnoe !!
@apates5  I believe you just need to type in "npm install cheerio" and hit enter. Delete "cd ....."

**Comment by apates5** [comment]
Ok thanks so much @Warnoe and @phu02 finally got it to work!

**Comment by nbclark** [comment]
Thanks for the comments here everyone. Added some troubleshooting tips to the readme
