### ISSUE TITLE
The best way to fine tune process image position

### ISSUE THREAD

**Issue by pjerryhu** [nbclark/hqcheat#5]
I'm guessing the javascript: 

```javascript
 const top = 400;
  const bottom = 900;
  const left = 150;
  var config1 = { width: 1174 - left - left, height: 2278 - top - bottom, top, left };
```

is used to crop out the question from newly added image on Desktop. 
Since I'm not using an iPhone X, what's the best strategy to fine-tune the position to make sure reading question is successfully ?

Thanks for reading!

**Comment by nbclark** [comment]
Hi @phu02 ,

It's more of an art than a science, but if you comment out https://github.com/nbclark/hqcheat/blob/master/index.js#L38 it will leave behind the cropped image so you can see how it was cropped. The dimensions I used are based off an iPhoneX mirrored to a MBP, so yours will likely be a bit different.

**Comment by mitopoietico** [comment]
Hallo @phu02, I'm on an iPhone SE mirrored on MBP. The script (after some installation problem) now works quite fine. But, sometimes, a question missing. Maybe the crop must be optimized for my screens. Do you have found better cropping sizes for older iPhone models?

**Comment by apates5** [comment]
@nbclark what do you mean comment out? Just take that part of the script out from it?
