### ISSUE TITLE
Mixing up questions and answers

### ISSUE THREAD

**Issue by apates5** [nbclark/hqcheat#7]
When I take a picture of the game it mixes up the question with the multiple choice answers. Does anyone know a fix to this? In this one is mixes up ambitious with the question.
<img width="654" alt="screen shot 2018-01-04 at 6 13 12 pm" src="https://user-images.githubusercontent.com/31677811/34588570-af5213da-f17b-11e7-92fa-3c2131d0af8f.png">

**Comment by rozay223** [comment]
Im getting this issue as well
Video I used from tonights game: 
https://www.youtube.com/watch?v=1ys7k_a8OLM
Question and options that got pulled:
Got question: "Walker, Texas Ranger" was co-created by the director of which Oscar-winning
Got options:  ﬁlm?,    ,
![image](https://user-images.githubusercontent.com/35089906/34594400-c3f3a6b4-f19e-11e7-9130-dc86e80b94ed.png)

Although some questions got pulled correctly:
Got question: \Q.‘ Which of these poetic forms is traditionally ﬁve lines long?                             
Got options:  Limerick, Sonnet, Haiku

**Comment by apates5** [comment]
Do you have any idea why this might happen? Or is it just a problem with Tesseract not being accurate?
