### ISSUE TITLE
Get rid of cropping image

### ISSUE THREAD

**Issue by apates5** [nbclark/hqcheat#8]
Does anyone know how I can edit the script so it doesn't crop the image it takes? Because on a mac you can do command shift 4 and you can select the part of the image you want to screenshot so there is no need to crop it, and then I can use this on any phone rather than just the iphone x. Thanks!

**Comment by AlexPerez01** [comment]
If you comment out line 38 that should do it..

// fs.unlink(`${path}.2`, () => { });

**Comment by apates5** [comment]
No I tried that all it does is show what was cropped not stop the cropping, but thanks for responding.

**Comment by betatesta144** [comment]
Did you ever figure this out lol
